site_name: Khonshu
site_url: https://freeletics.github.io/khonshu/
repo_name: Khonshu
repo_url: https://github.com/freeletics/khonshu
site_description: "Modern Android Development the Freeletics way"
site_author: Freeletics

copyright: 'Copyright &copy; 2021 Freeletics.'

theme:
  name: 'material'
  favicon: images/icon-freeletics.svg
  logo: images/logo-freeletics.svg
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - content.tabs.link
    - toc.integrate

nav:
  - index.md
  - 'Navigator':
      - navigation/get-started.md
      - navigation/activities.md
      - navigation/results.md
      - navigation/back-stacks.md
      - navigation/deeplinks.md
      - navigation/testing.md
      - 'API':
          - 'Runtime': navigation/API/runtime/index.html
          - 'Compose': navigation/API/compose/index.html
          - 'Testing': navigation/API/testing/index.html
  - 'Codegen':
      - codegen/get-started.md
      - codegen/activity-generation.md
      - codegen/compose-injection.md
      - codegen/closeable-support.md
      - 'API':
          - 'Runtime': codegen/API/runtime/index.html
  - 'Helpers':
      - helpers.md
      - 'API':
          - 'StateMachine': helpers/API/state-machine/index.html
          - 'StateMachineTesting': helpers/API/state-machine-testing/index.html
          - 'TextResource': helpers/API/text-resource/index.html
  - changelog.md

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
