package com.freeletics.khonshu.navigation

import androidx.compose.runtime.Composable
import com.freeletics.khonshu.navigation.internal.InternalNavigationTestingApi
import kotlin.reflect.KClass

/**
 * A combination of [Navigator] and [com.freeletics.khonshu.navigation.activity.ActivityNavigator] that can
 * be used as base class for navigators of individual screens.
 */
public abstract class DestinationNavigator(
    @property:InternalNavigationTestingApi
    public val hostNavigator: HostNavigator,
) : Navigator by hostNavigator,
    PlatformNavigator() {
    /**
     * See [HostNavigator.navigate].
     */
    public fun navigate(block: Navigator.() -> Unit) {
        hostNavigator.navigate(block)
    }
}

/**
 * A [Navigator] that is scoped to a single destination.
 *
 * Unlike [HostNavigator], which always operates on the back stack as a whole, this navigator knows
 * the exact back stack entry it was created for. That has two effects:
 *
 * - Operations that remove destinations from the back stack ([navigateBack], [navigateUp],
 *   [navigateBackTo] and [navigate]) are only executed while this navigator's destination is the
 *   current destination and are ignored otherwise. This makes it safe to trigger back navigation
 *   from a delayed callback or from repeated user input without accidentally removing a
 *   destination that was put on the back stack in the meantime.
 * - [registerForNavigationResult] resolves to this navigator's own destination instead of looking
 *   up a destination by route type, which is ambiguous when the same route is on the back stack
 *   more than once.
 *
 * Operations that add to the back stack or change which back stack is shown ([navigateTo],
 * [switchBackStack], [showRoot] and [replaceAllBackStacks]) are always executed.
 *
 * An implementation is automatically part of the dependency graph of destinations generated by
 * Khonshu's codegen, so this is usually not implemented manually. A navigator class for a specific
 * screen can delegate to the injected instance:
 *
 * ```kotlin
 * @Inject
 * @SingleIn(ExampleRoute::class)
 * class ExampleNavigator(
 *     navigator: DestinationNavigator2,
 * ) : DestinationNavigator2 by navigator
 * ```
 *
 * This is platform neutral and does not offer activity or permission navigation. Use
 * [DestinationNavigator]/[com.freeletics.khonshu.navigation.activity.ActivityNavigator] for those.
 */
public interface DestinationNavigator2 : Navigator {
    /**
     * Whether this navigator's destination is currently the current destination.
     *
     * While this is `false` all back navigation ([navigateBack], [navigateUp], [navigateBackTo] and
     * [navigate]) is ignored.
     *
     * When this is read from a `@Composable` function it is observed and the composable will be
     * recomposed whenever the value changes. It is meant to be used for enabling or disabling UI
     * and in tests. Navigation logic should generally not branch on it.
     */
    public val isCurrentDestination: Boolean

    /**
     * Triggers up navigation.
     *
     * This is a no-op while this navigator's destination is not the current destination, for
     * example because it was already removed from the back stack, because another destination was
     * put on top of it or because another back stack is being shown.
     */
    override fun navigateUp()

    /**
     * Removes the top entry from the back stack to show the previous destination.
     *
     * This is a no-op while this navigator's destination is not the current destination, for
     * example because it was already removed from the back stack, because another destination was
     * put on top of it or because another back stack is being shown.
     */
    override fun navigateBack()

    /**
     * Removes all entries from the back stack until [popUpTo]. If [inclusive] is `true` [popUpTo]
     * itself will also be removed.
     *
     * This is a no-op while this navigator's destination is not the current destination, for
     * example because it was already removed from the back stack, because another destination was
     * put on top of it or because another back stack is being shown.
     */
    override fun <T : BaseRoute> navigateBackTo(popUpTo: KClass<T>, inclusive: Boolean)

    /**
     * See [HostNavigator.navigate].
     *
     * This is a no-op while this navigator's destination is not the current destination, for
     * example because it was already removed from the back stack, because another destination was
     * put on top of it or because another back stack is being shown.
     *
     * Once the block runs, the operations inside of it are not guarded individually and behave
     * exactly like the equivalent [HostNavigator] operations, so that transitions like
     * [navigateBack] followed by [navigateTo] can be performed atomically.
     */
    public fun navigate(block: Navigator.() -> Unit)
}

public expect abstract class PlatformNavigator()

@Composable
public expect fun PlatformNavigatorEffect(navigator: PlatformNavigator)
