name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Install Android SDK
        run: ./.github/android-sdk.sh

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Build docs
        run: ./gradlew dokkaHtml

      - name: Copy docs
        run: |
          cp README.md docs/index.md
          cp navigator/README.md docs/navigator.md
          mkdir -p docs/API/navigator
          cp -R navigator/runtime/build/dokka/html/. docs/API/navigator/
          mkdir -p docs/API/navigator-compose
          cp -R navigator/runtime-compose/build/dokka/html/. docs/API/navigator-compose/
          mkdir -p docs/API/navigator-fragment
          cp -R navigator/runtime-fragment/build/dokka/html/. docs/API/navigator-fragment/
          mkdir -p docs/API/state-machine
          cp -R state-machine/build/dokka/html/. docs/API/state-machine/
          mkdir -p docs/API/text-resource
          cp -R text-resource/build/dokka/html/. docs/API/text-resource/
          cp whetstone/README.md docs/whetstone.md
          mkdir -p docs/API/whetstone
          cp -R whetstone/runtime/build/dokka/html/. docs/API/whetstone/
          mkdir -p docs/API/whetstone-compose
          cp -R whetstone/runtime-compose/build/dokka/html/. docs/API/whetstone-compose/
          mkdir -p docs/API/whetstone-fragment
          cp -R whetstone/runtime-fragment/build/dokka/html/. docs/API/whetstone-fragment/
          mkdir -p docs/API/whetstone-navigation
          cp -R whetstone/navigation/build/dokka/html/. docs/API/whetstone-navigation/
          mkdir -p docs/API/whetstone-navigation-compose
          cp -R whetstone/navigation-compose/build/dokka/html/. docs/API/whetstone-navigation-compose/
          mkdir -p docs/API/whetstone-navigation-fragment
          cp -R whetstone/navigation-fragment/build/dokka/html/. docs/API/whetstone-navigation-fragment/

      - name: Build MkDocs
        run: mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
