name: Publish Docs

on:
  push:
    branches:
      - main
  # TODO: replace with on push tag https://github.com/actions/deploy-pages/issues/76
  workflow_run:
    workflows: [Publish Release]
    types:
      - completed

jobs:
  publish:

    runs-on: ubuntu-latest
    if: github.repository == 'freeletics/mad'

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Install Android SDK
        run: ./.github/android-sdk.sh

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Build docs
        # need to set the version name because for the default committed snapshot version
        # dokkaHtml tasks get skipped
        run: ./gradlew dokkaHtml -PVERSION_NAME=

      - name: Copy docs
        run: |
          # copy shared filed
          cp README.md docs/index.md
          cp CHANGELOG.md docs/changelog.md
          # Update page title
          sed -i 's/# Modern Android Development - The Freeletics Way/# Overview/' docs/index.md
          # Set current version in docs
          sed -i "s/<latest-version>/$(git describe --tags --abbrev=0)/" docs/navigator/get-started.md
          sed -i "s/<latest-version>/$(git describe --tags --abbrev=0)/" docs/navigator/testing.md
          sed -i "s/<latest-version>/$(git describe --tags --abbrev=0)/" docs/whetstone/get-started.md
          sed -i "s/<latest-version>/$(git describe --tags --abbrev=0)/" docs/whetstone/navigation.md
          sed -i "s/<latest-version>/$(git describe --tags --abbrev=0)/" docs/helpers.md
          # Copy Dokka files
          mkdir -p docs/navigator/API/runtime
          cp -R navigator/runtime/build/dokka/html/. docs/navigator/API/runtime
          mkdir -p docs/navigator/API/runtime-compose
          cp -R navigator/runtime-compose/build/dokka/html/. docs/navigator/API/runtime-compose/
          mkdir -p docs/navigator/API/runtime-fragment
          cp -R navigator/runtime-fragment/build/dokka/html/. docs/navigator/API/runtime-fragment/
          mkdir -p docs/navigator/API/testing
          cp -R navigator/testing/build/dokka/html/. docs/navigator/API/testing/
          mkdir -p docs/helpers/API/state-machine
          cp -R state-machine/runtime/build/dokka/html/. docs/helpers/API/state-machine/
          mkdir -p docs/helpers/API/state-machine-testing
          cp -R state-machine/testing/build/dokka/html/. docs/helpers/API/state-machine-testing/
          mkdir -p docs/helpers/API/text-resource
          cp -R text-resource/build/dokka/html/. docs/helpers/API/text-resource/
          mkdir -p docs/whetstone/API/runtime
          cp -R whetstone/runtime/build/dokka/html/. docs/whetstone/API/runtime/
          mkdir -p docs/whetstone/API/runtime-compose
          cp -R whetstone/runtime-compose/build/dokka/html/. docs/whetstone/API/runtime-compose/
          mkdir -p docs/whetstone/API/runtime-fragment
          cp -R whetstone/runtime-fragment/build/dokka/html/. docs/whetstone/API/runtime-fragment/
          mkdir -p docs/whetstone/API/navigation
          cp -R whetstone/navigation/build/dokka/html/. docs/whetstone/API/navigation/
          mkdir -p docs/whetstone/API/navigation-compose
          cp -R whetstone/navigation-compose/build/dokka/html/. docs/whetstone/API/navigation-compose/
          mkdir -p docs/whetstone/API/navigation-fragment
          cp -R whetstone/navigation-fragment/build/dokka/html/. docs/whetstone/API/navigation-fragment/
          mkdir -p docs/whetstone/API/scope
          cp -R whetstone/scope/build/dokka/html/. docs/whetstone/API/scope/

      - name: Build MkDocs
        run: mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
